# GitLab CI/CD Pipeline für Potenzmengenkonstruktion
# Auto-Build & Deploy bei Änderungen + Trigger von Commons Updates

stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"
  APP_NAME: "potenzmengenkonstruktion"
  DEPLOY_PATH: "/usr/share/nginx/html/Potenzmengenkonstruktion"

# Build Stage - Holt neueste Commons Library und baut App
build_app:
  stage: build
  before_script:
    - echo "Node.js version:" && node --version && npm --version
    # SSH Setup für Commons Repository
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.w-hs.de >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Installing dependencies and updating commons library..."
    - npm ci --cache .npm --prefer-offline
    - echo "Building application..."
    - npm run build
    - echo "Build completed successfully"
    - ls -la dist/
  artifacts:
    paths:
      - dist/$APP_NAME/
    expire_in: 1 hour
  cache:
    paths:
      - .npm/
      - node_modules/
  only:
    - main
    - develop
    - /^release\/.*$/

# Deploy Stage - App lokal auf nginx Server deployen
deploy_to_server:
  stage: deploy
  script:
    - echo "Deploying to local nginx server..."
    
    # Backup erstellen (falls vorhanden)
    - |
      if [ -d '$DEPLOY_PATH' ]; then
        sudo cp -r '$DEPLOY_PATH' '${DEPLOY_PATH}.backup.$(date +%Y%m%d-%H%M%S)'
      fi
    
    # Deploy-Ordner vorbereiten
    - sudo mkdir -p '$DEPLOY_PATH'
    
    # Alte Version entfernen und neue Version kopieren
    - echo "Copying new version..."
    - sudo rm -rf '$DEPLOY_PATH'/*
    - sudo cp -r dist/$APP_NAME/* '$DEPLOY_PATH'/
    
    # Berechtigungen setzen
    - sudo chown -R www-data:www-data '$DEPLOY_PATH'
    - sudo chmod -R 755 '$DEPLOY_PATH'
    
    - echo "Successfully deployed to https://pi-lab.w-hs.de/Potenzmengenkonstruktion"
  dependencies:
    - build_app
  only:
    - main
  when: on_success
  environment:
    name: production
    url: https://pi-lab.w-hs.de/Potenzmengenkonstruktion